---
repos:
  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v0.13.0
    hooks:
      - id: detect-secrets
        args:
          - '--no-base64-string-scan'
          - '--baseline'
          - '.baseline'
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=25]
      - id: validate-toml
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy