---
name: Go Build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint
      - name: go vet
        run: go vet .
      - name: golint
        run: golint .
      - name: gofmt
        run: gofmt -l .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: go-critic
        run: |
          GO111MODULE=on go get -u github.com/go-critic/go-critic/cmd/gocritic
          gocritic check ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
