name: Publish release
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        VERSION=$(echo "${{ github.ref }}" | cut -d'/' -f3) make build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/semver*
        file_glob: true
        overwrite: true
        tag: ${{ github.ref }}